[general]
pidfile="burrow.pid"
stdout-logfile="burrow.out"

[logging]
filename="/tmp/burrow.log"
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[sasl.msk_dev]
username="admin"
password="admin"
mechanism="SCRAM-SHA-512"
handshake-first=true

[tls.msk_dev]
cafile="/tmp/truststore.pem"
noverify=true

[zookeeper]
servers=[ "xxx:2182", "xxx:2182", "xxx:2182" ]
timeout=10
root-path="/burrow"
tls="msk_dev"

[client-profile.msk-client_dev]
client-id="burrow-dev"
sasl="msk_dev"
tls="msk_dev"
kafka-version="2.7.0"

[cluster.msk_dev]
class-name="kafka"
servers=[ "xxx:9096", "xxx:9096", "xxx:9096" ]
client-profile="msk-client_dev"
topic-refresh=120
offset-refresh=30

[consumer.msk-cons_dev]
class-name="kafka"
cluster="msk_dev"
servers=[ "xxx:9096", "xxx:9096", "xxx:9096" ]
client-profile="msk-client_dev"
group-denylist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-allowlist=""

[httpserver.default]
address=":8000"

[storage.default]
class-name="inmemory"
workers=20
intervals=15
expire-group=604800
min-distance=1
