apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-burrow
  namespace: kafka
  labels:
    app: burrow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burrow
  template:
    metadata:
      labels:
        app: burrow
    spec:
      containers:
        - name: kafka-burrow
          image: rkferreira/burrow:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: burrow-svc
  name: kafka-burrow
  namespace: kafka
spec:
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: burrow
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx-private
    nginx.ingress.kubernetes.io/proxy-body-size: 1m
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: burrow-ingress
  namespace: kafka
spec:
  backend:
    serviceName: kafka-burrow
    servicePort: 8000
  rules:
  - host: kafka-burrow.mydomain.com
    http:
      paths:
      - backend:
          serviceName: kafka-burrow
          servicePort: 8000
        path: /

